# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS2020
  pod 'Alamofire'
  pod 'Kingfisher'
  target 'iOS2020Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS2020UITests' do
    # Pods for testing
  end

end
